import { mkdirSync, writeFileSync, existsSync } from 'fs';
import { join } from 'path';
import { execSync } from 'child_process';
import pino from 'pino';
import { ideaGet } from './db.js';

const log = pino({ name: 'nsaf.scaffolder' });

export function scaffoldProject(project, ports, dbInfo, preferences) {
  const dir = project.project_dir;

  // Create directory structure
  mkdirSync(join(dir, 'sdd-output'), { recursive: true });

  // Write vision document from idea metadata
  const idea = project.idea_id ? ideaGet(project.idea_id) : null;
  const visionDoc = buildVisionDocument(project, idea, preferences);
  writeFileSync(join(dir, 'sdd-output', 'vision-document.md'), visionDoc);

  // Write .env for the generated app
  const envContent = buildEnvFile(project, ports, dbInfo);
  writeFileSync(join(dir, '.env'), envContent);

  // Write .gitignore
  writeFileSync(join(dir, '.gitignore'), 'node_modules/\n.env\nsdd-output/\n');

  // Init git repo
  if (!existsSync(join(dir, '.git'))) {
    execSync('git init', { cwd: dir, stdio: 'pipe' });
    execSync('git add .gitignore', { cwd: dir, stdio: 'pipe' });
    execSync('git commit -m "Initial commit: NSAF scaffolded project"', {
      cwd: dir,
      stdio: 'pipe',
    });
  }

  log.info({ slug: project.slug, dir }, 'Project scaffolded');
  return dir;
}

function buildVisionDocument(project, idea, preferences) {
  const name = idea ? idea.name : project.slug;
  const description = idea ? idea.description : 'Auto-generated project';
  const category = idea ? idea.category : 'general';
  const complexity = idea ? idea.complexity : 'medium';

  let stack = {};
  if (idea && idea.suggested_stack) {
    try {
      stack = typeof idea.suggested_stack === 'string'
        ? JSON.parse(idea.suggested_stack)
        : idea.suggested_stack;
    } catch { /* use empty */ }
  }

  const stackStr = Object.entries(stack)
    .map(([k, v]) => `- **${k}**: ${v}`)
    .join('\n');

  return `# Vision Document: ${name}

## The Idea

${description}

## Problem Statement

This app addresses a need in the ${category} space. It was selected from NSAF's daily idea generation.

## Target Users

General users interested in ${category} applications.

## Success Criteria

- App is functional and deployed locally
- Core features work end-to-end
- Visually polished with custom artwork and animations
- Passes automated and manual QA checks

## Core Concepts

Category: ${category}
Complexity: ${complexity}

## Tech Stack

${stackStr || '- Use defaults from preferences'}

## Visual Design Requirements

This app MUST be visually rich and engaging — not basic or placeholder-looking. Specifically:

### Art Assets (REQUIRED)
You have access to MCP tools for generating art. USE THEM:

- **PixelLab MCP** — Use for pixel art sprites, characters, tiles, and game objects:
  - \`mcp__pixellab__create_character\` — Create character sprites with multiple directional views
  - \`mcp__pixellab__animate_character\` — Animate characters (walk, idle, attack, etc.)
  - \`mcp__pixellab__create_isometric_tile\` — Create isometric tiles for game maps
  - \`mcp__pixellab__create_topdown_tileset\` — Create top-down tilesets
  - \`mcp__pixellab__create_sidescroller_tileset\` — Create platformer tilesets
  - \`mcp__pixellab__create_map_object\` — Create objects like trees, buildings, items

- **Leonardo AI MCP** — Use for illustrations, backgrounds, icons, and UI art:
  - \`mcp__leonardo-ai__high_definition_generalist\` — General purpose high-quality images
  - \`mcp__leonardo-ai__hyperrealistic\` — Photorealistic images
  - \`mcp__leonardo-ai__accurate_text_rendering\` — Images with readable text

### Animation (REQUIRED)
- Use CSS animations, Framer Motion, or canvas-based animation
- Characters and game objects should move, react, and animate
- Transitions between screens should be smooth
- Idle animations, hover effects, particle effects where appropriate

### Visual Standards
- NO placeholder rectangles, colored divs, or emoji-as-sprites
- Every game object should have a real generated sprite or illustration
- Backgrounds should be illustrated, not solid colors
- UI should feel like a polished game, not a web form
- Color palette should be vibrant and age-appropriate

## Scope (MVP)

Build a complete, working web application with:
- Frontend with responsive UI and rich visual assets
- Backend API
- Database for persistent storage
- Core feature set as described above
- Generated art assets using PixelLab and/or Leonardo MCP tools

## Constraints

- Must be deployable locally on a single server
- Must use PostgreSQL for the database (connection string provided in .env)
- Port range allocated: ${preferences?.portStart || 'TBD'}-${preferences?.portEnd || 'TBD'}
`;
}

function buildEnvFile(project, ports, dbInfo) {
  const lines = [
    `# Generated by NSAF for project: ${project.slug}`,
    `PROJECT_NAME=${project.slug}`,
    `PORT=${ports.portStart}`,
    `PORT_RANGE_START=${ports.portStart}`,
    `PORT_RANGE_END=${ports.portEnd}`,
  ];

  if (dbInfo) {
    lines.push(`DATABASE_URL=${dbInfo.connectionString}`);
    lines.push(`DB_NAME=${dbInfo.dbName}`);
  }

  return lines.join('\n') + '\n';
}
