import { mkdirSync, writeFileSync, existsSync } from 'fs';
import { join } from 'path';
import { execSync } from 'child_process';
import pino from 'pino';
import { ideaGet } from './db.js';

const log = pino({ name: 'nsaf.scaffolder' });

export function scaffoldProject(project, ports, dbInfo, preferences) {
  const dir = project.project_dir;

  // Create directory structure
  mkdirSync(join(dir, 'sdd-output'), { recursive: true });

  // Write vision document from idea metadata
  const idea = project.idea_id ? ideaGet(project.idea_id) : null;
  const visionDoc = buildVisionDocument(project, idea, preferences);
  writeFileSync(join(dir, 'sdd-output', 'vision-document.md'), visionDoc);

  // Write .env for the generated app
  const envContent = buildEnvFile(project, ports, dbInfo);
  writeFileSync(join(dir, '.env'), envContent);

  // Write .gitignore
  writeFileSync(join(dir, '.gitignore'), 'node_modules/\n.env\nsdd-output/\n');

  // Init git repo
  if (!existsSync(join(dir, '.git'))) {
    execSync('git init', { cwd: dir, stdio: 'pipe' });
    execSync('git add .gitignore', { cwd: dir, stdio: 'pipe' });
    execSync('git commit -m "Initial commit: NSAF scaffolded project"', {
      cwd: dir,
      stdio: 'pipe',
    });
  }

  log.info({ slug: project.slug, dir }, 'Project scaffolded');
  return dir;
}

function buildVisionDocument(project, idea, preferences) {
  const name = idea ? idea.name : project.slug;
  const description = idea ? idea.description : 'Auto-generated project';
  const category = idea ? idea.category : 'general';
  const complexity = idea ? idea.complexity : 'medium';

  let stack = {};
  if (idea && idea.suggested_stack) {
    try {
      stack = typeof idea.suggested_stack === 'string'
        ? JSON.parse(idea.suggested_stack)
        : idea.suggested_stack;
    } catch { /* use empty */ }
  }

  const stackStr = Object.entries(stack)
    .map(([k, v]) => `- **${k}**: ${v}`)
    .join('\n');

  return `# Vision Document: ${name}

## The Idea

${description}

## Problem Statement

This app addresses a need in the ${category} space. It was selected from NSAF's daily idea generation.

## Target Users

General users interested in ${category} applications.

## Success Criteria

- App is functional and deployed locally
- Core features work end-to-end
- Passes automated and manual QA checks

## Core Concepts

Category: ${category}
Complexity: ${complexity}

## Tech Stack

${stackStr || '- Use defaults from preferences'}

## Scope (MVP)

Build a complete, working web application with:
- Frontend with responsive UI
- Backend API
- Database for persistent storage
- Core feature set as described above

## Constraints

- Must be deployable locally on a single server
- Must use PostgreSQL for the database (connection string provided in .env)
- Port range allocated: ${preferences?.portStart || 'TBD'}-${preferences?.portEnd || 'TBD'}
`;
}

function buildEnvFile(project, ports, dbInfo) {
  const lines = [
    `# Generated by NSAF for project: ${project.slug}`,
    `PROJECT_NAME=${project.slug}`,
    `PORT=${ports.portStart}`,
    `PORT_RANGE_START=${ports.portStart}`,
    `PORT_RANGE_END=${ports.portEnd}`,
  ];

  if (dbInfo) {
    lines.push(`DATABASE_URL=${dbInfo.connectionString}`);
    lines.push(`DB_NAME=${dbInfo.dbName}`);
  }

  return lines.join('\n') + '\n';
}
